#lang info
(define collection "cardano-wallet")
(define deps '("base" "fvm"))
(define build-deps '())
(define scribblings '())
(define racket-launcher-names '("cardano-wallet"))
(define racket-launcher-libraries '("main.rkt"))
(define pkg-desc "Cardano Wallet implementation in Racket, using the Fractalide Flow-Based Programming scheduler")
(define version "0.0")
(define pkg-authors '("claes.wallin@greatsinodevelopment.com"))
